apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ip-api-scaler
spec:
  scaleTargetRef:
    name: ip-api
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "30"
